### ISSUE TITLE
panic: inconsistent import: var time.UTC *time.Location

### ISSUE THREAD

**Issue by csstaub** [HewlettPackard/gas#9]
Running `gas` on https://github.com/square/ghostunnel results in a panic: 

```
cs ghostunnel master $ gas -exclude=vendor/ ./...
[gas]2016/07/25 11:42:51 Skipping /Users/cs/src/go/src/github.com/square/ghostunnel/.git
panic: inconsistent import:
	var time.UTC *time.Location
previously imported as:
	var UTC *time.Location
 [recovered]
	panic: inconsistent import:
	var time.UTC *time.Location
previously imported as:
	var UTC *time.Location


goroutine 1 [running]:
panic(0x25f640, 0xc42038d150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc42009a7e0, 0xc4203172c8)
	/usr/local/go/src/go/types/check.go:213 +0xae
panic(0x25f640, 0xc42038d150)
	/usr/local/go/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(*importer).declare(0xc42008c000, 0x3e3e20, 0xc4208be410)
	/usr/local/go/src/go/internal/gcimporter/bimport.go:173 +0x17c
go/internal/gcimporter.(*importer).obj(0xc42008c000, 0xfffffffffffffffc)
	/usr/local/go/src/go/internal/gcimporter/bimport.go:193 +0x1af
go/internal/gcimporter.BImportData(0xc4202adad0, 0xc420830000, 0x39d12, 0x3fe00, 0xc420332f31, 0x4, 0x0, 0x4, 0x0, 0x0)
	/usr/local/go/src/go/internal/gcimporter/bimport.go:86 +0x34c
go/internal/gcimporter.Import(0xc4202adad0, 0xc420332f31, 0x4, 0xc420098f00, 0x69, 0xc42027cff0, 0x0, 0x0)
	/usr/local/go/src/go/internal/gcimporter/gcimporter.go:166 +0x551
go/importer.gcimports.ImportFrom(0xc4202adad0, 0xc420332f31, 0x4, 0xc420098f00, 0x69, 0x0, 0x1, 0x2, 0x0)
	/usr/local/go/src/go/importer/importer.go:70 +0x67
go/types.(*Checker).collectObjects(0xc42009a7e0)
	/usr/local/go/src/go/types/resolver.go:191 +0x81d
go/types.(*Checker).checkFiles(0xc42009a7e0, 0xc4203173e0, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc42009a7e0, 0xc4203173e0, 0x1, 0x1, 0xc4202adb00, 0xfecef)
	/usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420393d80, 0x2bb247, 0x3, 0xc42000e7c0, 0xc4203173e0, 0x1, 0x1, 0xc4200c65a0, 0x0, 0x200000003, ...)
	/usr/local/go/src/go/types/api.go:344 +0x19f
github.com/HewlettPackard/gas/core.(*Analyzer).process(0xc4200b4b60, 0xc420098f00, 0x7a, 0x0, 0x0, 0xc420098f00, 0x0)
	/Users/cs/src/go/src/github.com/HewlettPackard/gas/core/analyzer.go:85 +0x38f
github.com/HewlettPackard/gas/core.(*Analyzer).Process(0xc4200b4b60, 0xc420098f00, 0x7a, 0x3, 0xc42001e001)
	/Users/cs/src/go/src/github.com/HewlettPackard/gas/core/analyzer.go:104 +0x55
main.main.func1(0xc420098f00, 0x7a, 0x3e2ee0, 0xc4202aa750, 0x0, 0x0, 0x0, 0x0)
	/Users/cs/src/go/src/github.com/HewlettPackard/gas/main.go:122 +0x151
path/filepath.walk(0xc420098f00, 0x7a, 0x3e2ee0, 0xc4202aa750, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:349 +0x81
path/filepath.walk(0xc4200caaf0, 0x69, 0x3e2ee0, 0xc4202aa680, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc4200e4f00, 0x5b, 0x3e2ee0, 0xc4202aa5b0, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc4200e4c60, 0x57, 0x3e2ee0, 0xc4202aa410, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc4200c63c0, 0x4c, 0x3e2ee0, 0xc4202aa340, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc4208fdcc0, 0x43, 0x3e2ee0, 0xc4202abee0, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc4203cdcc0, 0x38, 0x3e2ee0, 0xc4202abe10, 0xc420015bc0, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.walk(0xc42000e044, 0x31, 0x3e2ee0, 0xc42006da00, 0xc420015bc0, 0x0, 0x1)
	/usr/local/go/src/path/filepath/path.go:374 +0x344
path/filepath.Walk(0xc42000e044, 0x31, 0xc420015bc0, 0x0, 0x1)
	/usr/local/go/src/path/filepath/path.go:396 +0xd5
main.main()
	/Users/cs/src/go/src/github.com/HewlettPackard/gas/main.go:128 +0xd6d
```

Running `gas *.go` appears to work fine however.

This happened on gas built from 9ce14dc683934c1f285772aefa04c28671287c1b, built with go1.7 beta2.

**Comment by gcmurphy** [comment]
Interesting find! FWIW I tried with go version go1.6.2 darwin/amd64 and it ran to completion. Will try to reproduce using the beta. At the very least I think we need to do better than a panic if the importer fails.

**Comment by gcmurphy** [comment]
@csstaub This looks to be a similar bug: https://github.com/golang/go/issues/16027

Can you confirm the workaround of cleaning up $GOPATH/pkg resolves this issue for you?

**Comment by csstaub** [comment]
Huh, `rm -rf $GOPATH/pkg` did indeed fix the problem! Thanks @gcmurphy
